#!/usr/bin/env bash
# Generated by devstack — rebuild PHP with bundled extensions.
# Jika build gagal, edit hapus flag yang bermasalah lalu jalankan manual.
PHP_EXTRA_CONFIGURE_OPTIONS="--with-ffi --with-gmp --with-imap --with-kerberos --with-unixODBC --with-pdo-firebird --with-pdo-odbc --with-pgsql --with-snmp --with-sodium --with-tidy --with-xsl" mise install php@8.3 --force
