#!/usr/bin/env bash
# Generated by devstack — install PHP via mise + all bundled extensions.
# Jalankan di terminal interaktif (perlu sudo untuk apt).
# NOTE: pdo_odbc di-skip dulu karena plugin misinya tidak bisa menemukan header
#       unixODBC di /usr (plugin mengira ada di /usr/local). Jika mau diaktifkan
#       nanti, tambahkan: --with-pdo-odbc=unixODBC,/usr
set -e
sudo apt install -y libssl-dev libzip-dev libonig-dev libxml2-dev libpng-dev libicu-dev \
  libjpeg-dev libbz2-dev zlib1g-dev libcurl4-openssl-dev libtidy-dev \
  libsqlite3-dev libreadline-dev libgmp-dev libsodium-dev libfreetype6-dev \
  libwebp-dev libargon2-dev libpspell-dev libsnmp-dev libldap2-dev \
  unixodbc-dev libdb-dev libldb-dev libmcrypt-dev libgd-dev libxslt1-dev \
  libc-client2007e-dev libkrb5-dev firebird-dev libpq-dev
PHP_EXTRA_CONFIGURE_OPTIONS="--with-ffi --with-gmp --with-imap --with-kerberos --with-imap-ssl --with-unixODBC --with-pdo-firebird --with-pdo-pgsql --with-pgsql --with-snmp --with-sodium --with-tidy --with-xsl" mise install php@8.3 --force
mise reshim php
echo "DONE. Cek: php -m | grep -E 'pdo_pgsql|imap|pdo_firebird|tidy|xsl|snmp|pgsql|redis'"
