version: '3.8'

networks:
  dev-network:
    external: true

services:
  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog-dev
    restart: unless-stopped
    networks:
      - dev-network
    ports:
      - "${MAILHOG_SMTP_PORT:-1025}:1025"  # SMTP
      - "${MAILHOG_WEB_PORT:-8025}:8025"   # Web UI
