version: '3.8'

networks:
  dev-network:
    external: true

services:
  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog-dev
    restart: unless-stopped
    networks:
      - dev-network
    ports:
      - "1025:1025"  # SMTP
      - "8025:8025"  # Web UI
