version: '3.8'

networks:
  dev-network:
    external: true

services:
  postgres:
    image: postgres:15
    container_name: postgres15-dev
    restart: unless-stopped
    networks:
      - dev-network
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: app_pgdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

volumes:
  postgres_data:
    driver: local
